name = "velvet"
version = "0.1.0"
defaultTargets = ["velvet"]

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "v4.34.0"

[[lean_lib]]
name = "Velvet"

[[lean_lib]]
name = "Examples"
roots = ["Velvet.Examples"]
globs = ["Velvet.Examples.*"]
leanOptions = { sym.debug = true }

[[lean_exe]]
name = "velvet"
root = "Main"
