module

public import Velvet.Frontend.Method
public meta import Velvet.Frontend.Method
public import Velvet.Frontend.SyntaxDecls
public import Velvet.Core.Specs
public meta import Velvet.Core.Specs
public meta import Lean.Parser
public meta import Lean.Elab.Command
public import Std.WP

open Lean Elab Command Term Meta Lean.Parser Lean.Macro Std.WP

/-- Prove a method contract with `prove_correct foo`, producing the registered theorem
`foo.spec`. The generated abbreviation `foo.spec_triple` owns the complete quantified `Triple`;
this command only unfolds and proves that proposition. -/
@[incremental]
elab_rules : command
  | `(command| prove_correct $specId:ident by $proof:tacticSeq) => do
    let specIdent := mkIdentFrom specId (specId.getId ++ `spec_triple)
    let declName ← liftCoreM <| realizeGlobalConstNoOverload specIdent
    let info ← liftCoreM <| getConstInfo declName
    unless (← liftTermElabM <| whnf info.type).isProp do
      /- Fires when `prove_correct` targets a non-proposition, e.g. `prove_correct Nat.add by ...`. -/
      throwErrorAt specId "`{declName}` is not a proposition"
    /- Fires when the name has no method-contract metadata, e.g. a spec not generated by `method`. -/
    let some statement := methodSpecExt.getState (← getEnv) |>.get? declName
      | throwErrorAt specId "no method contract metadata found for `{declName}`"
    let statement : Term := ⟨statement⟩
    let proofId := mkIdentFrom specId (specId.getId ++ `spec)
    let thmCmd ← `(command|
      open scoped Std.WP Lean.Order in
      set_option linter.unusedVariables false in
      @[spec] public theorem $proofId : $statement :=
        show $specIdent from by
          unfold $specIdent
          ($proof))
    elabCommand thmCmd
