import Velvet
import Velvet.Examples.Loops
import Velvet.Examples.LoopsExplicitVCs
import Velvet.Examples.MaxElem
import Velvet.Examples.SumOfDigits
import Velvet.Examples.IsSorted
import Velvet.Examples.IsNonPrime
import Velvet.Examples.Sqrt
import Velvet.Examples.LoopControl
import Velvet.Examples.MatchRecursion
import Velvet.Examples.RunLengthEncoding
import Velvet.Examples.InsertionSort
import Velvet.Examples.Recursion
import Velvet.Examples.AutomaticExceptionInference
import Velvet.Examples.ErrorMsgs
import Velvet.Examples.StateT
import Velvet.Examples.StateTExplicitVCs
import Velvet.Examples.IntrinsicVerification
import Velvet.Examples.MemAlloc
import Velvet.Examples.HypNaming
import Velvet.Examples.LiftingExamples
import Velvet.Examples.VelvetAndIntrinsicVerification
